[package]
name = "rust_rest_api"
version = "0.1.0"
edition = "2024"


[dependencies]
reqwest = { version = "0.12.22", features = ["json", "rustls-tls"] }
serde = { version = "1.0.219", features = ["derive"] }
tokio = { version = "1.45.1", features = ["full"] }

